require('dotenv').config();
const express = require('express');
const app = express();
const mongoose = require('mongoose');
const session = require('express-session');
const MongoStore = require('connect-mongo');
const flash = require('connect-flash');
const routes = require("./routes");
const path = require('path');
const helmet = require('helmet');
const csrf = require('csurf');
